global using NUnit.Framework;
global using MTCG;
global using MTCG.Models;
global using MTCG.Interface;
global using MTCG.Services;
global using MTCG.Server;
global using MTCG.DAL;
global using MTCG.Controller;
global using Moq;
